<?php

namespace AppBundle\Repository;

/**
 * CategorySTEDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorySTEDataRepository extends \Doctrine\ORM\EntityRepository
{
}
