<?php

namespace AppBundle\Repository;

/**
 * EntryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
