<?php

namespace AppBundle\Repository;

/**
 * QuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
}
