<?php

namespace AppBundle\Repository;

/**
 * SeasonTypeEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonTypeEntryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFromCSD($csd) {
        $qb = $this->createQueryBuilder('ste')
            ->join('ste.type', 'type')
            ->addSelect('type')
            ->join('ste.entry', 'entry')
            ->addSelect('entry')
            ->join('ste.csd', 'csd')
            ->addSelect('csd')
            ->where('csd.id = :csd')
            ->setParameter('csd', $csd->getId())
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }
}
