<?php

namespace AppBundle\Repository;

/**
 * SiteSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
