<?php

namespace AppBundle\Repository;

/**
 * TestimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialRepository extends \Doctrine\ORM\EntityRepository
{
}
